package ru.kwanza.dbtool.orm.impl.mapping.entities;

import ru.kwanza.dbtool.orm.annotations.Entity;
import ru.kwanza.dbtool.orm.annotations.Fetch;
import ru.kwanza.dbtool.orm.annotations.Field;

import java.sql.Types;

/**
 * @author Kiryl Karatsetski
 */
@Entity(name = "PaymentTrx", tableName = "payment_trx")
public class PaymentTrx extends Trx {

    @Field(columnName = "amount", type = Types.BIGINT, autoGenerated = true)
    private Long amount;

    @Field(columnName = "full_amount")
    private transient Long fullAmount;

    @Field(columnName = "agent_id")
    private Long agentId;

    private Agent agent;

    @Fetch(propertyName = "agentId")
    public Agent getAgent() {
        return agent;
    }

    public void setAgent(Agent agent) {
        this.agent = agent;
    }

    private String description;

    @Field(columnName = "description")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
