package ru.kwanza.dbtool.orm.impl.mapping;

/**
 * @author Kiryl Karatsetski
 */
public class FieldMapping {
    private String name;
    private String column;
    public int type;
    private boolean autoGenerated;
    private EntityField entityField;

    public FieldMapping(String name, String column, int type, boolean autoGenerated, EntityField entityField) {
        this.name = name;
        this.column = column;
        this.type = type;
        this.autoGenerated = autoGenerated;
        this.entityField = entityField;
    }

    public String getColumn() {
        return column;
    }

    public int getType() {
        return type;
    }

    public String getName() {
        return name;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public EntityField getEntityFiled() {
        return this.entityField;
    }

    @Override
    public String toString() {
        final StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("FieldMapping{");
        stringBuilder.append("name='").append(name).append('\'');
        stringBuilder.append(", column='").append(column).append('\'');
        stringBuilder.append(", type=").append(type);
        stringBuilder.append(", autoGenerated=").append(autoGenerated);
        stringBuilder.append(", entityField=").append(entityField != null ? entityField.getClass() : null);
        stringBuilder.append('}');
        return stringBuilder.toString();
    }
}
