package ru.kwanza.dbtool.orm.impl.mapping;

import ru.kwanza.dbtool.orm.api.internal.IEntityType;
import ru.kwanza.dbtool.orm.api.internal.IFieldMapping;
import ru.kwanza.toolbox.fieldhelper.Property;

/**
 * @author Alexander Guzanov
 */
public class SubEntityFieldMapping implements IFieldMapping {
    private IEntityType entityType;
    private IFieldMapping originalField;
    private String column;

    public SubEntityFieldMapping(IEntityType entityType, IFieldMapping originalField) {
        this.entityType = entityType;
        this.originalField = originalField;
        this.column = entityType.getTableName() + "_" + originalField.getColumn();
    }

    public String getColumn() {
        return column;
    }

    public String getOriginalColumn() {
        return originalField.getColumn();
    }

    public int getType() {
        return originalField.getType();
    }

    public String getName() {
        return originalField.getName();
    }

    public boolean isAutoGenerated() {
        return originalField.isAutoGenerated();
    }

    public Property getProperty() {
        return originalField.getProperty();
    }
}
