package ru.kwanza.dbtool.orm.mapping;

/**
 * @author Kiryl Karatsetski
 */
public class FieldMapping {

    private String columnName;

    public int type;

    private boolean autoGenerated;

    private EntityField entityField;

    public FieldMapping(String columnName, int type, boolean autoGenerated, EntityField entityField) {
        this.columnName = columnName;
        this.type = type;
        this.autoGenerated = autoGenerated;
        this.entityField = entityField;
    }

    public String getColumnName() {
        return columnName;
    }

    public int getType() {
        return type;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public EntityField getEntityFiled() {
        return this.entityField;
    }
}
