package ru.kwanza.dbtool.orm.mapping;

/**
 * @author Alexander Guzanov
 */
public @interface IdField {

    String columnName() default "";

    int type() default Integer.MAX_VALUE;

    boolean autoGenerated() default false;
}
