CREATE TABLE TEST_TABLE
(
  xKEY NUMBER NOT NULL
, NAME VARCHAR2(255) NOT NULL
, VERSION NUMBER NOT NULL
, CONSTRAINT TEST_TABLE_PK PRIMARY KEY
  (
    XKEY
  )
  ENABLE
);

-- Unable to render TABLE DDL for object KWANZA.TEST_BLOB with DBMS_METADATA attempting internal generator.
CREATE TABLE TEST_BLOB
(
  VALUE BLOB
, ID NUMBER
) ;
-- Unable to render TABLE DDL for object KWANZA.TEST_TABLE1 with DBMS_METADATA attempting internal generator.
CREATE TABLE TEST_TABLE1
(
  XBOOL NUMBER(38, 0)
, XINT NUMBER(*, 0)
, XBIGINT NUMBER
, XSTRING VARCHAR2(256 BYTE)
, XTS1 TIMESTAMP(6)
, XTS2 TIMESTAMP(6)
, XBLOB BLOB
, XBIGDECIMAL NUMBER(*, 0)
);





