package ru.kwanza.dbtool.orm.annotations;

/**
 * @author Alexander Guzanov
 */
public @interface Field {

    String columnName() default "";

    int type() default Integer.MAX_VALUE;

    boolean autoGenerated() default false;
}
