package ru.kwanza.dbtool.orm.mapping;

import java.sql.Types;

/**
 * @author Alexander Guzanov
 */
public @interface Field {
    String columnName() default "";

    int type() default Integer.MAX_VALUE;

    boolean autoGenerated() default false;
}
